// Backward-compatible type exports for presentation layer.
// Source of truth lives in domain/shared/entities.ts.
export type {
  UserRole,
  OrderStatus,
  ProjectStatus,
  MoldType,
  Priority,
  ProcessCategory,
  ProcessStepStatus,
  WorkOrderStatus,
  MaterialCategory,
  PurchaseOrderStatus,
  StockMovementType,
  ToolType,
  SteelWeightMethod,
  SteelTagStatus,
  InspectionType,
  InspectionStatus,
  TryoutStatus,
  DefectType,
  PaymentType,
  PaymentMethod,
  PaymentStatus,
  PurchaseRequestStatus,
  Profile,
  Customer,
  Order,
  Project,
  ProcessStep,
  WorkOrder,
  WorkLog,
  Machine,
  Supplier,
  Material,
  SteelTag,
  Stock,
  StockMovement,
  PurchaseOrder,
  PurchaseOrderItem,
  QualityInspection,
  Tryout,
  Defect,
  Payment,
  MaterialPrice,
  PurchaseRequest,
  GLAccount,
  GLAccountType,
  JournalEntry,
  JournalEntryStatus,
  JournalLine,
  AROpenItem,
  AROpenItemStatus,
  APOpenItem,
  APOpenItemStatus,
  AccountingEvent,
  AccountingEventType,
  AccountingEventStatus,
  AccountingSourceType,
} from '@/domain/shared/entities';

export type QuoteStatus = 'DRAFT' | 'SUBMITTED' | 'ACCEPTED' | 'REJECTED' | 'EXPIRED';

// Re-export display maps from types/display.ts for backward compatibility
export {
  PROJECT_STATUS_MAP,
  ORDER_STATUS_MAP,
  WORK_ORDER_STATUS_MAP,
  MOLD_TYPE_MAP,
  PRIORITY_MAP,
  PROCESS_CATEGORY_MAP,
  SUPPLIER_TYPE_MAP,
  MATERIAL_CATEGORY_MAP,
  PO_STATUS_MAP,
  INSPECTION_TYPE_MAP,
  INSPECTION_STATUS_MAP,
  TRYOUT_STATUS_MAP,
  DEFECT_STATUS_MAP,
  DEFECT_TYPE_MAP,
  PAYMENT_TYPE_MAP,
  PAYMENT_METHOD_MAP,
  PAYMENT_STATUS_MAP,
  PR_STATUS_MAP,
  USER_ROLE_MAP,
  TOOL_TYPE_MAP,
  STEEL_WEIGHT_METHOD_MAP,
  STEEL_TAG_STATUS_MAP,
  STEEL_GRADE_DENSITY,
  JOURNAL_ENTRY_STATUS_MAP,
  AR_STATUS_MAP,
  AP_STATUS_MAP,
  ACCOUNTING_SOURCE_TYPE_MAP,
  GL_ACCOUNT_TYPE_MAP,
  ACCOUNTING_EVENT_STATUS_MAP,
} from './display';
